-- MySQL Script generated by MySQL Workbench
-- 10/06/14 23:19:03
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema e-assistant
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `e-assistant` ;
CREATE SCHEMA IF NOT EXISTS `e-assistant` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `e-assistant` ;

-- -----------------------------------------------------
-- Table `e-assistant`.`phone_numbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`phone_numbers` (
  `phone_number_id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` SMALLINT UNSIGNED NOT NULL,
  `number` VARCHAR(20) NOT NULL,
  `type` VARCHAR(45) NOT NULL DEFAULT 0,
  PRIMARY KEY (`phone_number_id`, `user_id`),
  INDEX `fk_phone_numbers_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_phone_numbers_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `e-assistant`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`email_addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`email_addresses` (
  `addr_id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` SMALLINT UNSIGNED NOT NULL,
  `address` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`addr_id`, `user_id`),
  INDEX `fk_email_addresses_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_email_addresses_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `e-assistant`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`groups` (
  `group_id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`users` (
  `user_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(25) NOT NULL,
  `password_hash` VARCHAR(40) NOT NULL,
  `date_registered` DATE NOT NULL,
  `date_hired` DATE NULL,
  `residence` VARCHAR(45) NULL,
  `function` VARCHAR(45) NULL,
  `main_phone_number_id` MEDIUMINT UNSIGNED NOT NULL,
  `main_addr_id` MEDIUMINT UNSIGNED NOT NULL,
  `group_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `main_phone_number_id`, `main_addr_id`, `group_id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  INDEX `fk_users_phone_numbers1_idx` (`main_phone_number_id` ASC),
  INDEX `fk_users_email_addresses1_idx` (`main_addr_id` ASC),
  INDEX `fk_users_groups1_idx` (`group_id` ASC),
  CONSTRAINT `fk_users_phone_numbers1`
    FOREIGN KEY (`main_phone_number_id`)
    REFERENCES `e-assistant`.`phone_numbers` (`phone_number_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_email_addresses1`
    FOREIGN KEY (`main_addr_id`)
    REFERENCES `e-assistant`.`email_addresses` (`addr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `e-assistant`.`groups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`messages` (
  `message_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `date_sent` DATETIME NOT NULL,
  PRIMARY KEY (`message_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`attachments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`attachments` (
  `attachment_id` MEDIUMINT UNSIGNED NOT NULL,
  `message_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `path` TEXT NOT NULL,
  PRIMARY KEY (`attachment_id`, `message_id`),
  INDEX `fk_attachments_messages1_idx` (`message_id` ASC),
  CONSTRAINT `fk_attachments_messages1`
    FOREIGN KEY (`message_id`)
    REFERENCES `e-assistant`.`messages` (`message_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`passports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`passports` (
  `idnp` VARCHAR(20) NOT NULL,
  `user_id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `registration` VARCHAR(45) NULL,
  `sex` CHAR NOT NULL DEFAULT 'M',
  `date_of_birth` DATE NULL,
  `date_of_issue` DATE NULL,
  `date_of_expiry` DATE NULL,
  `seria` VARCHAR(15) NULL,
  PRIMARY KEY (`idnp`, `user_id`),
  INDEX `fk_passports_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_passports_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `e-assistant`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`sessions` (
  `session_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` SMALLINT UNSIGNED NOT NULL,
  `php_session_id` VARCHAR(32) NOT NULL,
  `expires` DATETIME NOT NULL,
  PRIMARY KEY (`session_id`, `user_id`, `php_session_id`),
  INDEX `fk_sessions_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_sessions_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `e-assistant`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`destinations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`destinations` (
  `from_user_id` SMALLINT UNSIGNED NOT NULL,
  `to_user_id` SMALLINT UNSIGNED NOT NULL,
  `message_id` INT UNSIGNED NOT NULL,
  `date_read` DATETIME NULL DEFAULT NULL,
  `status` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`from_user_id`, `to_user_id`, `message_id`),
  INDEX `fk_destinations_users2_idx` (`to_user_id` ASC),
  INDEX `fk_destinations_messages1_idx` (`message_id` ASC),
  CONSTRAINT `fk_destinations_users1`
    FOREIGN KEY (`from_user_id`)
    REFERENCES `e-assistant`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_destinations_users2`
    FOREIGN KEY (`to_user_id`)
    REFERENCES `e-assistant`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_destinations_messages1`
    FOREIGN KEY (`message_id`)
    REFERENCES `e-assistant`.`messages` (`message_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`rights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`rights` (
  `right_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`right_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`group_rights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`group_rights` (
  `group_id` SMALLINT UNSIGNED NOT NULL,
  `right_id` INT NOT NULL,
  PRIMARY KEY (`group_id`, `right_id`),
  INDEX `fk_group_rights_rights1_idx` (`right_id` ASC),
  CONSTRAINT `fk_group_rights_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `e-assistant`.`groups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_rights_rights1`
    FOREIGN KEY (`right_id`)
    REFERENCES `e-assistant`.`rights` (`right_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`user_rights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`user_rights` (
  `user_id` SMALLINT UNSIGNED NOT NULL,
  `right_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `right_id`),
  INDEX `fk_user_rights_rights1_idx` (`right_id` ASC),
  CONSTRAINT `fk_user_rights_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `e-assistant`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_rights_rights1`
    FOREIGN KEY (`right_id`)
    REFERENCES `e-assistant`.`rights` (`right_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
