-- MySQL Script generated by MySQL Workbench
-- 10/05/14 21:45:49
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema e-assistant
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `e-assistant` ;
CREATE SCHEMA IF NOT EXISTS `e-assistant` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `e-assistant` ;

-- -----------------------------------------------------
-- Table `e-assistant`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`users` (
  `user_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(25) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `function` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`messages` (
  `message_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `date_sent` DATETIME NOT NULL,
  PRIMARY KEY (`message_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`addressees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`addressees` (
  `addressee_user_id` SMALLINT UNSIGNED NOT NULL,
  `addresser_user_id` SMALLINT UNSIGNED NOT NULL,
  `message_id` INT UNSIGNED NOT NULL,
  `status` TINYINT UNSIGNED NULL DEFAULT 0,
  `date_read` DATETIME NULL,
  PRIMARY KEY (`addressee_user_id`, `addresser_user_id`, `message_id`),
  INDEX `fk_addressees_users1_idx` (`addresser_user_id` ASC),
  INDEX `fk_addressees_messages1_idx` (`message_id` ASC),
  INDEX `fk_addressees_users2_idx` (`addressee_user_id` ASC),
  CONSTRAINT `fk_addressees_users1`
    FOREIGN KEY (`addresser_user_id`)
    REFERENCES `e-assistant`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_addressees_messages1`
    FOREIGN KEY (`message_id`)
    REFERENCES `e-assistant`.`messages` (`message_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_addressees_users2`
    FOREIGN KEY (`addressee_user_id`)
    REFERENCES `e-assistant`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`attachments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`attachments` (
  `attachment_id` MEDIUMINT UNSIGNED NOT NULL,
  `message_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `path` TEXT NOT NULL,
  PRIMARY KEY (`attachment_id`, `message_id`),
  INDEX `fk_attachments_messages1_idx` (`message_id` ASC),
  CONSTRAINT `fk_attachments_messages1`
    FOREIGN KEY (`message_id`)
    REFERENCES `e-assistant`.`messages` (`message_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`passports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`passports` (
  `idnp` VARCHAR(20) NOT NULL,
  `user_id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `sex` CHAR NOT NULL DEFAULT 'M',
  PRIMARY KEY (`idnp`, `user_id`),
  INDEX `fk_passports_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_passports_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `e-assistant`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`sessions` (
  `session_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` SMALLINT UNSIGNED NOT NULL,
  `php_session_id` VARCHAR(32) NOT NULL,
  `expires` DATETIME NOT NULL,
  PRIMARY KEY (`session_id`, `user_id`, `php_session_id`),
  INDEX `fk_sessions_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_sessions_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `e-assistant`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
