-- MySQL Script generated by MySQL Workbench
-- 10/12/14 02:02:45
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema e-assistant
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `e-assistant` ;
CREATE SCHEMA IF NOT EXISTS `e-assistant` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `e-assistant` ;

-- -----------------------------------------------------
-- Table `e-assistant`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`groups` (
  `group_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`users` (
  `user_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_id` TINYINT UNSIGNED NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `date_registered` DATE NULL,
  `date_employed` DATE NULL,
  `date_fired` DATE NULL,
  `salary` DECIMAL(10,5) NULL,
  `premium` SMALLINT NULL,
  `function` VARCHAR(45) NULL,
  `status` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`user_id`, `group_id`),
  INDEX `fk_users_groups1_idx` (`group_id` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  CONSTRAINT `fk_users_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `e-assistant`.`groups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`passports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`passports` (
  `passport_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` SMALLINT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `gender` CHAR NULL,
  `blood_type` VARCHAR(5) NULL,
  `idnp` VARCHAR(15) NOT NULL,
  `seria` VARCHAR(15) NULL,
  `citizenship` VARCHAR(10) NULL,
  `residence` VARCHAR(45) NULL,
  `issued_by` VARCHAR(45) NULL,
  `date_born` DATE NULL,
  `date_issued` DATE NULL,
  `date_expires` DATE NULL,
  PRIMARY KEY (`passport_id`, `user_id`),
  UNIQUE INDEX `idnp_UNIQUE` (`idnp` ASC),
  INDEX `fk_passports_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_passports_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `e-assistant`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`messages` (
  `message_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id_from` SMALLINT UNSIGNED NOT NULL,
  `user_id_to` SMALLINT UNSIGNED NOT NULL,
  `text` VARCHAR(45) NOT NULL,
  `date_sent` DATETIME NOT NULL,
  `date_read` DATETIME NULL,
  PRIMARY KEY (`message_id`, `user_id_from`, `user_id_to`),
  INDEX `fk_messages_users1_idx` (`user_id_from` ASC),
  INDEX `fk_messages_users2_idx` (`user_id_to` ASC),
  CONSTRAINT `fk_messages_users1`
    FOREIGN KEY (`user_id_from`)
    REFERENCES `e-assistant`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_users2`
    FOREIGN KEY (`user_id_to`)
    REFERENCES `e-assistant`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`sessions` (
  `session_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` SMALLINT UNSIGNED NOT NULL,
  `phpsessid` VARCHAR(45) NOT NULL,
  `expires` DATETIME NOT NULL,
  PRIMARY KEY (`session_id`, `user_id`),
  INDEX `fk_sessions_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_sessions_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `e-assistant`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '			';


-- -----------------------------------------------------
-- Table `e-assistant`.`attachments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`attachments` (
  `attachment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `message_id` INT UNSIGNED NOT NULL,
  `filename` VARCHAR(45) NOT NULL,
  `path` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`attachment_id`, `message_id`),
  INDEX `fk_attachments_messages1_idx` (`message_id` ASC),
  CONSTRAINT `fk_attachments_messages1`
    FOREIGN KEY (`message_id`)
    REFERENCES `e-assistant`.`messages` (`message_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`phone_number_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`phone_number_types` (
  `phone_number_type_id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`phone_number_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`phone_numbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`phone_numbers` (
  `phone_number_id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phone_number_type_id` MEDIUMINT UNSIGNED NOT NULL,
  `user_id` SMALLINT UNSIGNED NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `is_main` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`phone_number_id`, `phone_number_type_id`, `user_id`),
  INDEX `fk_phone_numbers_phone_number_types1_idx` (`phone_number_type_id` ASC),
  INDEX `fk_phone_numbers_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_phone_numbers_phone_number_types1`
    FOREIGN KEY (`phone_number_type_id`)
    REFERENCES `e-assistant`.`phone_number_types` (`phone_number_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phone_numbers_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `e-assistant`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-assistant`.`email_addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-assistant`.`email_addresses` (
  `email_address_id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `users_user_id` SMALLINT UNSIGNED NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `is_main` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`email_address_id`, `users_user_id`),
  INDEX `fk_email_addresses_users1_idx` (`users_user_id` ASC),
  CONSTRAINT `fk_email_addresses_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `e-assistant`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
